project:
  output-dir: docs
  type: website

website:
  title: "QR - Analysis at UATX"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
      background: "#D9E3E4"
      pinned: true
      align: left
      contents:
        - href: about.qmd
          text: "About"
        - href: "One-minute.qmd"
          text: "One-minute questions"
        - href: "https://dtkaplan.github.io/QR-A"
          text: "QRA textbook"
        - href: "weeks.qmd"
          text: "Weekly materials"

format: 
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

# Enable webR
webr:
  channel-type: 'automatic'
  repos: ["https://dtkaplan.r-universe.dev"]
  packages: ['mosaicCalc', 'ggplot2', 'ggformula', "dplyr"]
filters:
  - live
  - shinylive
